### ISSUE TITLE
 ValueError

### ISSUE THREAD

**Issue by Chx121386** [luisgarciar/3D-bin-packing#6]
Hello, can you tell me whether the 3D boxing test of the PPO environment is successful? Here I display: ValueError: operators could not be broadcast together with shapes (10,) (3,) (10,). How can I handle this error?

**Comment by Chx121386** [comment]
Hello!
The previous error reports have been resolved, but now when running the train.py file, an error will be reported: TypeError: tuple indications must be integers or slices, not str. What is the cause.

**Comment by luisgarciar** [comment]
Hi, 

The train.py script should work now. Be sure also to check the jupyter notebooks in the nb folder; these have more examples of training the models.
